### ISSUE TITLE
final_plot.png

### ISSUE THREAD

**Issue by Ryman1262645** [Ryman1262645/HelloWorld#4]
The x axis is labled 2^0 through 2^15 instead of 2^10 through 2^26 which we should fix when we add the mac data

**Comment by ts-scik** [comment]
Eitan specified that our x-axis has to be Kilobytes instead of bytes, so every x value is divided by 1024.
So 2^10 bytes becomes 2^0 kilobytes, 2^26 bytes becomes 2^15 kilobytes, etc
